/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TrainingRouteImport } from './routes/training'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrainingIndexRouteImport } from './routes/training.index'
import { Route as ServicesIndexRouteImport } from './routes/services.index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as TrainingSlugRouteImport } from './routes/training.$slug'
import { Route as ServicesProductDevelopmentRouteImport } from './routes/services.product-development'
import { Route as ServicesMobileWebRouteImport } from './routes/services.mobile-web'
import { Route as ServicesIndustrialAutomationRouteImport } from './routes/services.industrial-automation'
import { Route as ServicesHealthcareRouteImport } from './routes/services.healthcare'
import { Route as ServicesEmbeddedSystemsRouteImport } from './routes/services.embedded-systems'
import { Route as ServicesEdgeAiTinymlRouteImport } from './routes/services.edge-ai-tinyml'
import { Route as ServicesCloudBackendRouteImport } from './routes/services.cloud-backend'
import { Route as ServicesAiotRouteImport } from './routes/services.aiot'
import { Route as ServicesSlugRouteImport } from './routes/services.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const TrainingRoute = TrainingRouteImport.update({
  id: '/training',
  path: '/training',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrainingIndexRoute = TrainingIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TrainingRoute,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const TrainingSlugRoute = TrainingSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TrainingRoute,
} as any)
const ServicesProductDevelopmentRoute =
  ServicesProductDevelopmentRouteImport.update({
    id: '/product-development',
    path: '/product-development',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesMobileWebRoute = ServicesMobileWebRouteImport.update({
  id: '/mobile-web',
  path: '/mobile-web',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesIndustrialAutomationRoute =
  ServicesIndustrialAutomationRouteImport.update({
    id: '/industrial-automation',
    path: '/industrial-automation',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesHealthcareRoute = ServicesHealthcareRouteImport.update({
  id: '/healthcare',
  path: '/healthcare',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesEmbeddedSystemsRoute = ServicesEmbeddedSystemsRouteImport.update({
  id: '/embedded-systems',
  path: '/embedded-systems',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesEdgeAiTinymlRoute = ServicesEdgeAiTinymlRouteImport.update({
  id: '/edge-ai-tinyml',
  path: '/edge-ai-tinyml',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesCloudBackendRoute = ServicesCloudBackendRouteImport.update({
  id: '/cloud-backend',
  path: '/cloud-backend',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesAiotRoute = ServicesAiotRouteImport.update({
  id: '/aiot',
  path: '/aiot',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ServicesRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/training': typeof TrainingRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/aiot': typeof ServicesAiotRoute
  '/services/cloud-backend': typeof ServicesCloudBackendRoute
  '/services/edge-ai-tinyml': typeof ServicesEdgeAiTinymlRoute
  '/services/embedded-systems': typeof ServicesEmbeddedSystemsRoute
  '/services/healthcare': typeof ServicesHealthcareRoute
  '/services/industrial-automation': typeof ServicesIndustrialAutomationRoute
  '/services/mobile-web': typeof ServicesMobileWebRoute
  '/services/product-development': typeof ServicesProductDevelopmentRoute
  '/training/$slug': typeof TrainingSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/training/': typeof TrainingIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/aiot': typeof ServicesAiotRoute
  '/services/cloud-backend': typeof ServicesCloudBackendRoute
  '/services/edge-ai-tinyml': typeof ServicesEdgeAiTinymlRoute
  '/services/embedded-systems': typeof ServicesEmbeddedSystemsRoute
  '/services/healthcare': typeof ServicesHealthcareRoute
  '/services/industrial-automation': typeof ServicesIndustrialAutomationRoute
  '/services/mobile-web': typeof ServicesMobileWebRoute
  '/services/product-development': typeof ServicesProductDevelopmentRoute
  '/training/$slug': typeof TrainingSlugRoute
  '/blog': typeof BlogIndexRoute
  '/services': typeof ServicesIndexRoute
  '/training': typeof TrainingIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/privacy': typeof PrivacyRoute
  '/services': typeof ServicesRouteWithChildren
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/terms': typeof TermsRoute
  '/training': typeof TrainingRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/services/aiot': typeof ServicesAiotRoute
  '/services/cloud-backend': typeof ServicesCloudBackendRoute
  '/services/edge-ai-tinyml': typeof ServicesEdgeAiTinymlRoute
  '/services/embedded-systems': typeof ServicesEmbeddedSystemsRoute
  '/services/healthcare': typeof ServicesHealthcareRoute
  '/services/industrial-automation': typeof ServicesIndustrialAutomationRoute
  '/services/mobile-web': typeof ServicesMobileWebRoute
  '/services/product-development': typeof ServicesProductDevelopmentRoute
  '/training/$slug': typeof TrainingSlugRoute
  '/blog/': typeof BlogIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/training/': typeof TrainingIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/privacy'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/training'
    | '/blog/$slug'
    | '/services/$slug'
    | '/services/aiot'
    | '/services/cloud-backend'
    | '/services/edge-ai-tinyml'
    | '/services/embedded-systems'
    | '/services/healthcare'
    | '/services/industrial-automation'
    | '/services/mobile-web'
    | '/services/product-development'
    | '/training/$slug'
    | '/blog/'
    | '/services/'
    | '/training/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/contact'
    | '/privacy'
    | '/sitemap.xml'
    | '/terms'
    | '/blog/$slug'
    | '/services/$slug'
    | '/services/aiot'
    | '/services/cloud-backend'
    | '/services/edge-ai-tinyml'
    | '/services/embedded-systems'
    | '/services/healthcare'
    | '/services/industrial-automation'
    | '/services/mobile-web'
    | '/services/product-development'
    | '/training/$slug'
    | '/blog'
    | '/services'
    | '/training'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/blog'
    | '/contact'
    | '/privacy'
    | '/services'
    | '/sitemap.xml'
    | '/terms'
    | '/training'
    | '/blog/$slug'
    | '/services/$slug'
    | '/services/aiot'
    | '/services/cloud-backend'
    | '/services/edge-ai-tinyml'
    | '/services/embedded-systems'
    | '/services/healthcare'
    | '/services/industrial-automation'
    | '/services/mobile-web'
    | '/services/product-development'
    | '/training/$slug'
    | '/blog/'
    | '/services/'
    | '/training/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  PrivacyRoute: typeof PrivacyRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  TermsRoute: typeof TermsRoute
  TrainingRoute: typeof TrainingRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/training': {
      id: '/training'
      path: '/training'
      fullPath: '/training'
      preLoaderRoute: typeof TrainingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/training/': {
      id: '/training/'
      path: '/'
      fullPath: '/training/'
      preLoaderRoute: typeof TrainingIndexRouteImport
      parentRoute: typeof TrainingRoute
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/training/$slug': {
      id: '/training/$slug'
      path: '/$slug'
      fullPath: '/training/$slug'
      preLoaderRoute: typeof TrainingSlugRouteImport
      parentRoute: typeof TrainingRoute
    }
    '/services/product-development': {
      id: '/services/product-development'
      path: '/product-development'
      fullPath: '/services/product-development'
      preLoaderRoute: typeof ServicesProductDevelopmentRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/mobile-web': {
      id: '/services/mobile-web'
      path: '/mobile-web'
      fullPath: '/services/mobile-web'
      preLoaderRoute: typeof ServicesMobileWebRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/industrial-automation': {
      id: '/services/industrial-automation'
      path: '/industrial-automation'
      fullPath: '/services/industrial-automation'
      preLoaderRoute: typeof ServicesIndustrialAutomationRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/healthcare': {
      id: '/services/healthcare'
      path: '/healthcare'
      fullPath: '/services/healthcare'
      preLoaderRoute: typeof ServicesHealthcareRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/embedded-systems': {
      id: '/services/embedded-systems'
      path: '/embedded-systems'
      fullPath: '/services/embedded-systems'
      preLoaderRoute: typeof ServicesEmbeddedSystemsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/edge-ai-tinyml': {
      id: '/services/edge-ai-tinyml'
      path: '/edge-ai-tinyml'
      fullPath: '/services/edge-ai-tinyml'
      preLoaderRoute: typeof ServicesEdgeAiTinymlRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/cloud-backend': {
      id: '/services/cloud-backend'
      path: '/cloud-backend'
      fullPath: '/services/cloud-backend'
      preLoaderRoute: typeof ServicesCloudBackendRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/aiot': {
      id: '/services/aiot'
      path: '/aiot'
      fullPath: '/services/aiot'
      preLoaderRoute: typeof ServicesAiotRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/$slug': {
      id: '/services/$slug'
      path: '/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ServicesRouteChildren {
  ServicesSlugRoute: typeof ServicesSlugRoute
  ServicesAiotRoute: typeof ServicesAiotRoute
  ServicesCloudBackendRoute: typeof ServicesCloudBackendRoute
  ServicesEdgeAiTinymlRoute: typeof ServicesEdgeAiTinymlRoute
  ServicesEmbeddedSystemsRoute: typeof ServicesEmbeddedSystemsRoute
  ServicesHealthcareRoute: typeof ServicesHealthcareRoute
  ServicesIndustrialAutomationRoute: typeof ServicesIndustrialAutomationRoute
  ServicesMobileWebRoute: typeof ServicesMobileWebRoute
  ServicesProductDevelopmentRoute: typeof ServicesProductDevelopmentRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesSlugRoute: ServicesSlugRoute,
  ServicesAiotRoute: ServicesAiotRoute,
  ServicesCloudBackendRoute: ServicesCloudBackendRoute,
  ServicesEdgeAiTinymlRoute: ServicesEdgeAiTinymlRoute,
  ServicesEmbeddedSystemsRoute: ServicesEmbeddedSystemsRoute,
  ServicesHealthcareRoute: ServicesHealthcareRoute,
  ServicesIndustrialAutomationRoute: ServicesIndustrialAutomationRoute,
  ServicesMobileWebRoute: ServicesMobileWebRoute,
  ServicesProductDevelopmentRoute: ServicesProductDevelopmentRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

interface TrainingRouteChildren {
  TrainingSlugRoute: typeof TrainingSlugRoute
  TrainingIndexRoute: typeof TrainingIndexRoute
}

const TrainingRouteChildren: TrainingRouteChildren = {
  TrainingSlugRoute: TrainingSlugRoute,
  TrainingIndexRoute: TrainingIndexRoute,
}

const TrainingRouteWithChildren = TrainingRoute._addFileChildren(
  TrainingRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  PrivacyRoute: PrivacyRoute,
  ServicesRoute: ServicesRouteWithChildren,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  TermsRoute: TermsRoute,
  TrainingRoute: TrainingRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
